apiVersion: 1

datasources:
  - name: priceMonitor
    uid: priceMonitor
    type: postgres
    access: proxy
    url: db:5432
    user: postgres
    isDefault: true
    jsonData:
      database: price_monitor
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
    secureJsonData:
      password: $__env{DB_PASSWORD}
